// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/google/uuid"
)

// ActivateSceneParams is parameters of activate_scene operation.
type ActivateSceneParams struct {
	RoomName  string
	SceneName string
}

// DeleteAlarmParams is parameters of deleteAlarm operation.
type DeleteAlarmParams struct {
	AlarmID uuid.UUID
}

// DisableAlarmParams is parameters of disableAlarm operation.
type DisableAlarmParams struct {
	AlarmID uuid.UUID
}

// DismissAlarmParams is parameters of dismissAlarm operation.
type DismissAlarmParams struct {
	AlarmID uuid.UUID
}

// EnableAlarmParams is parameters of enableAlarm operation.
type EnableAlarmParams struct {
	AlarmID uuid.UUID
}

// GetAlarmParams is parameters of getAlarm operation.
type GetAlarmParams struct {
	AlarmID uuid.UUID
}

// GetRoomParams is parameters of get_room operation.
type GetRoomParams struct {
	RoomName string
}

// ListOccurrencesParams is parameters of listOccurrences operation.
type ListOccurrencesParams struct {
	AlarmID uuid.UUID
	Limit   OptInt `json:",omitempty,omitzero"`
}

// ListSoundsParams is parameters of list_sounds operation.
type ListSoundsParams struct {
	Category OptSoundCategory `json:",omitempty,omitzero"`
}

// SnoozeAlarmParams is parameters of snoozeAlarm operation.
type SnoozeAlarmParams struct {
	AlarmID uuid.UUID
}
