// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type AccessToken struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *AccessToken) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *AccessToken) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *AccessToken) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *AccessToken) SetRoles(val []string) {
	s.Roles = val
}

// ActivateSceneNoContent is response for ActivateScene operation.
type ActivateSceneNoContent struct{}

func (*ActivateSceneNoContent) activateSceneRes() {}

// Ref: #/components/schemas/AlarmCreate
type AlarmCreate struct {
	Label    string         `json:"label"`
	Schedule ScheduleSchema `json:"schedule"`
	RoomName string         `json:"room_name"`
	// Defaults to the default profile.
	ProfileID OptNilUUID `json:"profile_id"`
}

// GetLabel returns the value of Label.
func (s *AlarmCreate) GetLabel() string {
	return s.Label
}

// GetSchedule returns the value of Schedule.
func (s *AlarmCreate) GetSchedule() ScheduleSchema {
	return s.Schedule
}

// GetRoomName returns the value of RoomName.
func (s *AlarmCreate) GetRoomName() string {
	return s.RoomName
}

// GetProfileID returns the value of ProfileID.
func (s *AlarmCreate) GetProfileID() OptNilUUID {
	return s.ProfileID
}

// SetLabel sets the value of Label.
func (s *AlarmCreate) SetLabel(val string) {
	s.Label = val
}

// SetSchedule sets the value of Schedule.
func (s *AlarmCreate) SetSchedule(val ScheduleSchema) {
	s.Schedule = val
}

// SetRoomName sets the value of RoomName.
func (s *AlarmCreate) SetRoomName(val string) {
	s.RoomName = val
}

// SetProfileID sets the value of ProfileID.
func (s *AlarmCreate) SetProfileID(val OptNilUUID) {
	s.ProfileID = val
}

// Ref: #/components/schemas/AlarmRead
type AlarmRead struct {
	ID             uuid.UUID      `json:"id"`
	Label          string         `json:"label"`
	Schedule       ScheduleSchema `json:"schedule"`
	RoomName       string         `json:"room_name"`
	ProfileID      uuid.UUID      `json:"profile_id"`
	IsEnabled      bool           `json:"is_enabled"`
	CreatedAt      time.Time      `json:"created_at"`
	NextOccurrence NilDateTime    `json:"next_occurrence"`
}

// GetID returns the value of ID.
func (s *AlarmRead) GetID() uuid.UUID {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *AlarmRead) GetLabel() string {
	return s.Label
}

// GetSchedule returns the value of Schedule.
func (s *AlarmRead) GetSchedule() ScheduleSchema {
	return s.Schedule
}

// GetRoomName returns the value of RoomName.
func (s *AlarmRead) GetRoomName() string {
	return s.RoomName
}

// GetProfileID returns the value of ProfileID.
func (s *AlarmRead) GetProfileID() uuid.UUID {
	return s.ProfileID
}

// GetIsEnabled returns the value of IsEnabled.
func (s *AlarmRead) GetIsEnabled() bool {
	return s.IsEnabled
}

// GetCreatedAt returns the value of CreatedAt.
func (s *AlarmRead) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetNextOccurrence returns the value of NextOccurrence.
func (s *AlarmRead) GetNextOccurrence() NilDateTime {
	return s.NextOccurrence
}

// SetID sets the value of ID.
func (s *AlarmRead) SetID(val uuid.UUID) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *AlarmRead) SetLabel(val string) {
	s.Label = val
}

// SetSchedule sets the value of Schedule.
func (s *AlarmRead) SetSchedule(val ScheduleSchema) {
	s.Schedule = val
}

// SetRoomName sets the value of RoomName.
func (s *AlarmRead) SetRoomName(val string) {
	s.RoomName = val
}

// SetProfileID sets the value of ProfileID.
func (s *AlarmRead) SetProfileID(val uuid.UUID) {
	s.ProfileID = val
}

// SetIsEnabled sets the value of IsEnabled.
func (s *AlarmRead) SetIsEnabled(val bool) {
	s.IsEnabled = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *AlarmRead) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetNextOccurrence sets the value of NextOccurrence.
func (s *AlarmRead) SetNextOccurrence(val NilDateTime) {
	s.NextOccurrence = val
}

func (*AlarmRead) createAlarmRes()  {}
func (*AlarmRead) disableAlarmRes() {}
func (*AlarmRead) enableAlarmRes()  {}
func (*AlarmRead) getAlarmRes()     {}

// Where alarm and preview audio is played.
// Ref: #/components/schemas/AudioOutput
type AudioOutput string

const (
	AudioOutputLocal AudioOutput = "local"
	AudioOutputSonos AudioOutput = "sonos"
)

// AllValues returns all AudioOutput values.
func (AudioOutput) AllValues() []AudioOutput {
	return []AudioOutput{
		AudioOutputLocal,
		AudioOutputSonos,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AudioOutput) MarshalText() ([]byte, error) {
	switch s {
	case AudioOutputLocal:
		return []byte(s), nil
	case AudioOutputSonos:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AudioOutput) UnmarshalText(data []byte) error {
	switch AudioOutput(data) {
	case AudioOutputLocal:
		*s = AudioOutputLocal
		return nil
	case AudioOutputSonos:
		*s = AudioOutputSonos
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// The device sounds are currently played on.
// Ref: #/components/schemas/AudioOutputRead
type AudioOutputRead struct {
	Active    AudioOutput   `json:"active"`
	Available []AudioOutput `json:"available"`
}

// GetActive returns the value of Active.
func (s *AudioOutputRead) GetActive() AudioOutput {
	return s.Active
}

// GetAvailable returns the value of Available.
func (s *AudioOutputRead) GetAvailable() []AudioOutput {
	return s.Available
}

// SetActive sets the value of Active.
func (s *AudioOutputRead) SetActive(val AudioOutput) {
	s.Active = val
}

// SetAvailable sets the value of Available.
func (s *AudioOutputRead) SetAvailable(val []AudioOutput) {
	s.Available = val
}

func (*AudioOutputRead) selectAudioOutputRes() {}

// Ref: #/components/schemas/AudioOutputRequest
type AudioOutputRequest struct {
	// The output to play on from now on.
	Output AudioOutput `json:"output"`
}

// GetOutput returns the value of Output.
func (s *AudioOutputRequest) GetOutput() AudioOutput {
	return s.Output
}

// SetOutput sets the value of Output.
func (s *AudioOutputRequest) SetOutput(val AudioOutput) {
	s.Output = val
}

// DeleteAlarmNoContent is response for DeleteAlarm operation.
type DeleteAlarmNoContent struct{}

func (*DeleteAlarmNoContent) deleteAlarmRes() {}

// Ref: #/components/schemas/HTTPValidationError
type HTTPValidationError struct {
	Detail []ValidationError `json:"detail"`
}

// GetDetail returns the value of Detail.
func (s *HTTPValidationError) GetDetail() []ValidationError {
	return s.Detail
}

// SetDetail sets the value of Detail.
func (s *HTTPValidationError) SetDetail(val []ValidationError) {
	s.Detail = val
}

func (*HTTPValidationError) activateSceneRes()     {}
func (*HTTPValidationError) createAlarmRes()       {}
func (*HTTPValidationError) createProfileRes()     {}
func (*HTTPValidationError) deleteAlarmRes()       {}
func (*HTTPValidationError) disableAlarmRes()      {}
func (*HTTPValidationError) dismissAlarmRes()      {}
func (*HTTPValidationError) enableAlarmRes()       {}
func (*HTTPValidationError) getAlarmRes()          {}
func (*HTTPValidationError) getRoomRes()           {}
func (*HTTPValidationError) listOccurrencesRes()   {}
func (*HTTPValidationError) listSoundsRes()        {}
func (*HTTPValidationError) previewSoundRes()      {}
func (*HTTPValidationError) selectAudioOutputRes() {}
func (*HTTPValidationError) setVolumeRes()         {}
func (*HTTPValidationError) snoozeAlarmRes()       {}

// Ref: #/components/schemas/IntroSchema
type IntroSchema struct {
	// Id of a sound from GET /sounds, e.g. 'wake_up/bowls'.
	SoundID uuid.UUID `json:"sound_id"`
}

// GetSoundID returns the value of SoundID.
func (s *IntroSchema) GetSoundID() uuid.UUID {
	return s.SoundID
}

// SetSoundID sets the value of SoundID.
func (s *IntroSchema) SetSoundID(val uuid.UUID) {
	s.SoundID = val
}

type ListOccurrencesOKApplicationJSON []OccurrenceRead

func (*ListOccurrencesOKApplicationJSON) listOccurrencesRes() {}

type ListSoundsOKApplicationJSON []SoundRead

func (*ListSoundsOKApplicationJSON) listSoundsRes() {}

// NewNilDateTime returns new NilDateTime with value set to v.
func NewNilDateTime(v time.Time) NilDateTime {
	return NilDateTime{
		Value: v,
	}
}

// NilDateTime is nullable time.Time.
type NilDateTime struct {
	Value time.Time
	Null  bool
}

// SetTo sets value to v.
func (o *NilDateTime) SetTo(v time.Time) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilDateTime) SetToNull() {
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OccurrenceRead
type OccurrenceRead struct {
	ID            uuid.UUID       `json:"id"`
	AlarmID       uuid.UUID       `json:"alarm_id"`
	ScheduledFor  time.Time       `json:"scheduled_for"`
	State         OccurrenceState `json:"state"`
	TriggeredAt   NilDateTime     `json:"triggered_at"`
	FinishedAt    NilDateTime     `json:"finished_at"`
	SnoozeCount   int             `json:"snooze_count"`
	FailureReason NilString       `json:"failure_reason"`
}

// GetID returns the value of ID.
func (s *OccurrenceRead) GetID() uuid.UUID {
	return s.ID
}

// GetAlarmID returns the value of AlarmID.
func (s *OccurrenceRead) GetAlarmID() uuid.UUID {
	return s.AlarmID
}

// GetScheduledFor returns the value of ScheduledFor.
func (s *OccurrenceRead) GetScheduledFor() time.Time {
	return s.ScheduledFor
}

// GetState returns the value of State.
func (s *OccurrenceRead) GetState() OccurrenceState {
	return s.State
}

// GetTriggeredAt returns the value of TriggeredAt.
func (s *OccurrenceRead) GetTriggeredAt() NilDateTime {
	return s.TriggeredAt
}

// GetFinishedAt returns the value of FinishedAt.
func (s *OccurrenceRead) GetFinishedAt() NilDateTime {
	return s.FinishedAt
}

// GetSnoozeCount returns the value of SnoozeCount.
func (s *OccurrenceRead) GetSnoozeCount() int {
	return s.SnoozeCount
}

// GetFailureReason returns the value of FailureReason.
func (s *OccurrenceRead) GetFailureReason() NilString {
	return s.FailureReason
}

// SetID sets the value of ID.
func (s *OccurrenceRead) SetID(val uuid.UUID) {
	s.ID = val
}

// SetAlarmID sets the value of AlarmID.
func (s *OccurrenceRead) SetAlarmID(val uuid.UUID) {
	s.AlarmID = val
}

// SetScheduledFor sets the value of ScheduledFor.
func (s *OccurrenceRead) SetScheduledFor(val time.Time) {
	s.ScheduledFor = val
}

// SetState sets the value of State.
func (s *OccurrenceRead) SetState(val OccurrenceState) {
	s.State = val
}

// SetTriggeredAt sets the value of TriggeredAt.
func (s *OccurrenceRead) SetTriggeredAt(val NilDateTime) {
	s.TriggeredAt = val
}

// SetFinishedAt sets the value of FinishedAt.
func (s *OccurrenceRead) SetFinishedAt(val NilDateTime) {
	s.FinishedAt = val
}

// SetSnoozeCount sets the value of SnoozeCount.
func (s *OccurrenceRead) SetSnoozeCount(val int) {
	s.SnoozeCount = val
}

// SetFailureReason sets the value of FailureReason.
func (s *OccurrenceRead) SetFailureReason(val NilString) {
	s.FailureReason = val
}

func (*OccurrenceRead) dismissAlarmRes() {}
func (*OccurrenceRead) snoozeAlarmRes()  {}

// Ref: #/components/schemas/OccurrenceState
type OccurrenceState string

const (
	OccurrenceStatePending   OccurrenceState = "pending"
	OccurrenceStateSunrise   OccurrenceState = "sunrise"
	OccurrenceStateRinging   OccurrenceState = "ringing"
	OccurrenceStateSnoozed   OccurrenceState = "snoozed"
	OccurrenceStateDismissed OccurrenceState = "dismissed"
	OccurrenceStateSkipped   OccurrenceState = "skipped"
	OccurrenceStateFailed    OccurrenceState = "failed"
)

// AllValues returns all OccurrenceState values.
func (OccurrenceState) AllValues() []OccurrenceState {
	return []OccurrenceState{
		OccurrenceStatePending,
		OccurrenceStateSunrise,
		OccurrenceStateRinging,
		OccurrenceStateSnoozed,
		OccurrenceStateDismissed,
		OccurrenceStateSkipped,
		OccurrenceStateFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OccurrenceState) MarshalText() ([]byte, error) {
	switch s {
	case OccurrenceStatePending:
		return []byte(s), nil
	case OccurrenceStateSunrise:
		return []byte(s), nil
	case OccurrenceStateRinging:
		return []byte(s), nil
	case OccurrenceStateSnoozed:
		return []byte(s), nil
	case OccurrenceStateDismissed:
		return []byte(s), nil
	case OccurrenceStateSkipped:
		return []byte(s), nil
	case OccurrenceStateFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OccurrenceState) UnmarshalText(data []byte) error {
	switch OccurrenceState(data) {
	case OccurrenceStatePending:
		*s = OccurrenceStatePending
		return nil
	case OccurrenceStateSunrise:
		*s = OccurrenceStateSunrise
		return nil
	case OccurrenceStateRinging:
		*s = OccurrenceStateRinging
		return nil
	case OccurrenceStateSnoozed:
		*s = OccurrenceStateSnoozed
		return nil
	case OccurrenceStateDismissed:
		*s = OccurrenceStateDismissed
		return nil
	case OccurrenceStateSkipped:
		*s = OccurrenceStateSkipped
		return nil
	case OccurrenceStateFailed:
		*s = OccurrenceStateFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSoundCategory returns new OptSoundCategory with value set to v.
func NewOptSoundCategory(v SoundCategory) OptSoundCategory {
	return OptSoundCategory{
		Value: v,
		Set:   true,
	}
}

// OptSoundCategory is optional SoundCategory.
type OptSoundCategory struct {
	Value SoundCategory
	Set   bool
}

// IsSet returns true if OptSoundCategory was set.
func (o OptSoundCategory) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSoundCategory) Reset() {
	var v SoundCategory
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSoundCategory) SetTo(v SoundCategory) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSoundCategory) Get() (v SoundCategory, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSoundCategory) Or(d SoundCategory) SoundCategory {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSunriseSchema returns new OptSunriseSchema with value set to v.
func NewOptSunriseSchema(v SunriseSchema) OptSunriseSchema {
	return OptSunriseSchema{
		Value: v,
		Set:   true,
	}
}

// OptSunriseSchema is optional SunriseSchema.
type OptSunriseSchema struct {
	Value SunriseSchema
	Set   bool
}

// IsSet returns true if OptSunriseSchema was set.
func (o OptSunriseSchema) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSunriseSchema) Reset() {
	var v SunriseSchema
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSunriseSchema) SetTo(v SunriseSchema) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSunriseSchema) Get() (v SunriseSchema, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSunriseSchema) Or(d SunriseSchema) SunriseSchema {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ProfileCreate
type ProfileCreate struct {
	Name     string           `json:"name"`
	Intro    IntroSchema      `json:"intro"`
	Ringtone RingtoneSchema   `json:"ringtone"`
	Sunrise  OptSunriseSchema `json:"sunrise"`
}

// GetName returns the value of Name.
func (s *ProfileCreate) GetName() string {
	return s.Name
}

// GetIntro returns the value of Intro.
func (s *ProfileCreate) GetIntro() IntroSchema {
	return s.Intro
}

// GetRingtone returns the value of Ringtone.
func (s *ProfileCreate) GetRingtone() RingtoneSchema {
	return s.Ringtone
}

// GetSunrise returns the value of Sunrise.
func (s *ProfileCreate) GetSunrise() OptSunriseSchema {
	return s.Sunrise
}

// SetName sets the value of Name.
func (s *ProfileCreate) SetName(val string) {
	s.Name = val
}

// SetIntro sets the value of Intro.
func (s *ProfileCreate) SetIntro(val IntroSchema) {
	s.Intro = val
}

// SetRingtone sets the value of Ringtone.
func (s *ProfileCreate) SetRingtone(val RingtoneSchema) {
	s.Ringtone = val
}

// SetSunrise sets the value of Sunrise.
func (s *ProfileCreate) SetSunrise(val OptSunriseSchema) {
	s.Sunrise = val
}

// Everything a profile is created with, plus what the server owns.
// Ref: #/components/schemas/ProfileRead
type ProfileRead struct {
	Name      string           `json:"name"`
	Intro     IntroSchema      `json:"intro"`
	Ringtone  RingtoneSchema   `json:"ringtone"`
	Sunrise   OptSunriseSchema `json:"sunrise"`
	ID        uuid.UUID        `json:"id"`
	IsDefault bool             `json:"is_default"`
}

// GetName returns the value of Name.
func (s *ProfileRead) GetName() string {
	return s.Name
}

// GetIntro returns the value of Intro.
func (s *ProfileRead) GetIntro() IntroSchema {
	return s.Intro
}

// GetRingtone returns the value of Ringtone.
func (s *ProfileRead) GetRingtone() RingtoneSchema {
	return s.Ringtone
}

// GetSunrise returns the value of Sunrise.
func (s *ProfileRead) GetSunrise() OptSunriseSchema {
	return s.Sunrise
}

// GetID returns the value of ID.
func (s *ProfileRead) GetID() uuid.UUID {
	return s.ID
}

// GetIsDefault returns the value of IsDefault.
func (s *ProfileRead) GetIsDefault() bool {
	return s.IsDefault
}

// SetName sets the value of Name.
func (s *ProfileRead) SetName(val string) {
	s.Name = val
}

// SetIntro sets the value of Intro.
func (s *ProfileRead) SetIntro(val IntroSchema) {
	s.Intro = val
}

// SetRingtone sets the value of Ringtone.
func (s *ProfileRead) SetRingtone(val RingtoneSchema) {
	s.Ringtone = val
}

// SetSunrise sets the value of Sunrise.
func (s *ProfileRead) SetSunrise(val OptSunriseSchema) {
	s.Sunrise = val
}

// SetID sets the value of ID.
func (s *ProfileRead) SetID(val uuid.UUID) {
	s.ID = val
}

// SetIsDefault sets the value of IsDefault.
func (s *ProfileRead) SetIsDefault(val bool) {
	s.IsDefault = val
}

func (*ProfileRead) createProfileRes() {}

// Ref: #/components/schemas/RingtoneSchema
type RingtoneSchema struct {
	// Id of a sound from GET /sounds, e.g. 'wake_up/bowls'.
	SoundID uuid.UUID `json:"sound_id"`
	Volume  OptInt    `json:"volume"`
}

// GetSoundID returns the value of SoundID.
func (s *RingtoneSchema) GetSoundID() uuid.UUID {
	return s.SoundID
}

// GetVolume returns the value of Volume.
func (s *RingtoneSchema) GetVolume() OptInt {
	return s.Volume
}

// SetSoundID sets the value of SoundID.
func (s *RingtoneSchema) SetSoundID(val uuid.UUID) {
	s.SoundID = val
}

// SetVolume sets the value of Volume.
func (s *RingtoneSchema) SetVolume(val OptInt) {
	s.Volume = val
}

// Ref: #/components/schemas/RoomRead
type RoomRead struct {
	Name       string   `json:"name"`
	SceneNames []string `json:"scene_names"`
}

// GetName returns the value of Name.
func (s *RoomRead) GetName() string {
	return s.Name
}

// GetSceneNames returns the value of SceneNames.
func (s *RoomRead) GetSceneNames() []string {
	return s.SceneNames
}

// SetName sets the value of Name.
func (s *RoomRead) SetName(val string) {
	s.Name = val
}

// SetSceneNames sets the value of SceneNames.
func (s *RoomRead) SetSceneNames(val []string) {
	s.SceneNames = val
}

func (*RoomRead) getRoomRes() {}

// When an alarm fires, as wall-clock time in a named zone.
// Ref: #/components/schemas/ScheduleSchema
type ScheduleSchema struct {
	Hour   int `json:"hour"`
	Minute int `json:"minute"`
	// IANA zone. The alarm keeps its wall-clock time across DST.
	Timezone OptString `json:"timezone"`
	// Empty means the alarm fires once, then disables itself.
	Days []Weekday `json:"days"`
}

// GetHour returns the value of Hour.
func (s *ScheduleSchema) GetHour() int {
	return s.Hour
}

// GetMinute returns the value of Minute.
func (s *ScheduleSchema) GetMinute() int {
	return s.Minute
}

// GetTimezone returns the value of Timezone.
func (s *ScheduleSchema) GetTimezone() OptString {
	return s.Timezone
}

// GetDays returns the value of Days.
func (s *ScheduleSchema) GetDays() []Weekday {
	return s.Days
}

// SetHour sets the value of Hour.
func (s *ScheduleSchema) SetHour(val int) {
	s.Hour = val
}

// SetMinute sets the value of Minute.
func (s *ScheduleSchema) SetMinute(val int) {
	s.Minute = val
}

// SetTimezone sets the value of Timezone.
func (s *ScheduleSchema) SetTimezone(val OptString) {
	s.Timezone = val
}

// SetDays sets the value of Days.
func (s *ScheduleSchema) SetDays(val []Weekday) {
	s.Days = val
}

// SetVolumeNoContent is response for SetVolume operation.
type SetVolumeNoContent struct{}

func (*SetVolumeNoContent) setVolumeRes() {}

// Ref: #/components/schemas/SnoozeRequest
type SnoozeRequest struct {
	Minutes OptInt `json:"minutes"`
}

// GetMinutes returns the value of Minutes.
func (s *SnoozeRequest) GetMinutes() OptInt {
	return s.Minutes
}

// SetMinutes sets the value of Minutes.
func (s *SnoozeRequest) SetMinutes(val OptInt) {
	s.Minutes = val
}

// Ref: #/components/schemas/SoundCategory
type SoundCategory string

const (
	SoundCategoryWakeUp SoundCategory = "wake_up"
	SoundCategoryGetUp  SoundCategory = "get_up"
)

// AllValues returns all SoundCategory values.
func (SoundCategory) AllValues() []SoundCategory {
	return []SoundCategory{
		SoundCategoryWakeUp,
		SoundCategoryGetUp,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SoundCategory) MarshalText() ([]byte, error) {
	switch s {
	case SoundCategoryWakeUp:
		return []byte(s), nil
	case SoundCategoryGetUp:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SoundCategory) UnmarshalText(data []byte) error {
	switch SoundCategory(data) {
	case SoundCategoryWakeUp:
		*s = SoundCategoryWakeUp
		return nil
	case SoundCategoryGetUp:
		*s = SoundCategoryGetUp
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SoundPreviewRequest
type SoundPreviewRequest struct {
	SoundID uuid.UUID `json:"sound_id"`
	Volume  OptInt    `json:"volume"`
}

// GetSoundID returns the value of SoundID.
func (s *SoundPreviewRequest) GetSoundID() uuid.UUID {
	return s.SoundID
}

// GetVolume returns the value of Volume.
func (s *SoundPreviewRequest) GetVolume() OptInt {
	return s.Volume
}

// SetSoundID sets the value of SoundID.
func (s *SoundPreviewRequest) SetSoundID(val uuid.UUID) {
	s.SoundID = val
}

// SetVolume sets the value of Volume.
func (s *SoundPreviewRequest) SetVolume(val OptInt) {
	s.Volume = val
}

// A sound as an alarm profile refers to it.
// Ref: #/components/schemas/SoundRead
type SoundRead struct {
	// Store this UUID in a profile.
	ID       uuid.UUID     `json:"id"`
	Name     string        `json:"name"`
	Category SoundCategory `json:"category"`
}

// GetID returns the value of ID.
func (s *SoundRead) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *SoundRead) GetName() string {
	return s.Name
}

// GetCategory returns the value of Category.
func (s *SoundRead) GetCategory() SoundCategory {
	return s.Category
}

// SetID sets the value of ID.
func (s *SoundRead) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *SoundRead) SetName(val string) {
	s.Name = val
}

// SetCategory sets the value of Category.
func (s *SoundRead) SetCategory(val SoundCategory) {
	s.Category = val
}

func (*SoundRead) previewSoundRes() {}

// StopPlaybackNoContent is response for StopPlayback operation.
type StopPlaybackNoContent struct{}

// Ref: #/components/schemas/SunriseSchema
type SunriseSchema struct {
	// Name of a Hue scene from GET /rooms/{room_name}.
	SceneName       OptString `json:"scene_name"`
	DurationMinutes OptInt    `json:"duration_minutes"`
	BrightnessStart OptInt    `json:"brightness_start"`
	BrightnessEnd   OptInt    `json:"brightness_end"`
}

// GetSceneName returns the value of SceneName.
func (s *SunriseSchema) GetSceneName() OptString {
	return s.SceneName
}

// GetDurationMinutes returns the value of DurationMinutes.
func (s *SunriseSchema) GetDurationMinutes() OptInt {
	return s.DurationMinutes
}

// GetBrightnessStart returns the value of BrightnessStart.
func (s *SunriseSchema) GetBrightnessStart() OptInt {
	return s.BrightnessStart
}

// GetBrightnessEnd returns the value of BrightnessEnd.
func (s *SunriseSchema) GetBrightnessEnd() OptInt {
	return s.BrightnessEnd
}

// SetSceneName sets the value of SceneName.
func (s *SunriseSchema) SetSceneName(val OptString) {
	s.SceneName = val
}

// SetDurationMinutes sets the value of DurationMinutes.
func (s *SunriseSchema) SetDurationMinutes(val OptInt) {
	s.DurationMinutes = val
}

// SetBrightnessStart sets the value of BrightnessStart.
func (s *SunriseSchema) SetBrightnessStart(val OptInt) {
	s.BrightnessStart = val
}

// SetBrightnessEnd sets the value of BrightnessEnd.
func (s *SunriseSchema) SetBrightnessEnd(val OptInt) {
	s.BrightnessEnd = val
}

// Ref: #/components/schemas/ValidationError
type ValidationError struct {
	Loc  []ValidationErrorLocItem `json:"loc"`
	Msg  string                   `json:"msg"`
	Type string                   `json:"type"`
}

// GetLoc returns the value of Loc.
func (s *ValidationError) GetLoc() []ValidationErrorLocItem {
	return s.Loc
}

// GetMsg returns the value of Msg.
func (s *ValidationError) GetMsg() string {
	return s.Msg
}

// GetType returns the value of Type.
func (s *ValidationError) GetType() string {
	return s.Type
}

// SetLoc sets the value of Loc.
func (s *ValidationError) SetLoc(val []ValidationErrorLocItem) {
	s.Loc = val
}

// SetMsg sets the value of Msg.
func (s *ValidationError) SetMsg(val string) {
	s.Msg = val
}

// SetType sets the value of Type.
func (s *ValidationError) SetType(val string) {
	s.Type = val
}

// ValidationErrorLocItem represents sum type.
type ValidationErrorLocItem struct {
	Type   ValidationErrorLocItemType // switch on this field
	String string
	Int    int
}

// ValidationErrorLocItemType is oneOf type of ValidationErrorLocItem.
type ValidationErrorLocItemType string

// Possible values for ValidationErrorLocItemType.
const (
	StringValidationErrorLocItem ValidationErrorLocItemType = "string"
	IntValidationErrorLocItem    ValidationErrorLocItemType = "int"
)

// IsString reports whether ValidationErrorLocItem is string.
func (s ValidationErrorLocItem) IsString() bool { return s.Type == StringValidationErrorLocItem }

// IsInt reports whether ValidationErrorLocItem is int.
func (s ValidationErrorLocItem) IsInt() bool { return s.Type == IntValidationErrorLocItem }

// SetString sets ValidationErrorLocItem to string.
func (s *ValidationErrorLocItem) SetString(v string) {
	s.Type = StringValidationErrorLocItem
	s.String = v
}

// GetString returns string and true boolean if ValidationErrorLocItem is string.
func (s ValidationErrorLocItem) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringValidationErrorLocItem returns new ValidationErrorLocItem from string.
func NewStringValidationErrorLocItem(v string) ValidationErrorLocItem {
	var s ValidationErrorLocItem
	s.SetString(v)
	return s
}

// SetInt sets ValidationErrorLocItem to int.
func (s *ValidationErrorLocItem) SetInt(v int) {
	s.Type = IntValidationErrorLocItem
	s.Int = v
}

// GetInt returns int and true boolean if ValidationErrorLocItem is int.
func (s ValidationErrorLocItem) GetInt() (v int, ok bool) {
	if !s.IsInt() {
		return v, false
	}
	return s.Int, true
}

// NewIntValidationErrorLocItem returns new ValidationErrorLocItem from int.
func NewIntValidationErrorLocItem(v int) ValidationErrorLocItem {
	var s ValidationErrorLocItem
	s.SetInt(v)
	return s
}

// Ref: #/components/schemas/VolumeRequest
type VolumeRequest struct {
	Volume int `json:"volume"`
}

// GetVolume returns the value of Volume.
func (s *VolumeRequest) GetVolume() int {
	return s.Volume
}

// SetVolume sets the value of Volume.
func (s *VolumeRequest) SetVolume(val int) {
	s.Volume = val
}

// Ref: #/components/schemas/Weekday
type Weekday int

const (
	Weekday0 Weekday = 0
	Weekday1 Weekday = 1
	Weekday2 Weekday = 2
	Weekday3 Weekday = 3
	Weekday4 Weekday = 4
	Weekday5 Weekday = 5
	Weekday6 Weekday = 6
)

// AllValues returns all Weekday values.
func (Weekday) AllValues() []Weekday {
	return []Weekday{
		Weekday0,
		Weekday1,
		Weekday2,
		Weekday3,
		Weekday4,
		Weekday5,
		Weekday6,
	}
}
