// Code generated by ogen, DO NOT EDIT.
package api

type ActivateSceneRes interface {
	activateSceneRes()
}

type CreateAlarmRes interface {
	createAlarmRes()
}

type CreateProfileRes interface {
	createProfileRes()
}

type DeleteAlarmRes interface {
	deleteAlarmRes()
}

type DisableAlarmRes interface {
	disableAlarmRes()
}

type DismissAlarmRes interface {
	dismissAlarmRes()
}

type EnableAlarmRes interface {
	enableAlarmRes()
}

type GetAlarmRes interface {
	getAlarmRes()
}

type GetRoomRes interface {
	getRoomRes()
}

type ListOccurrencesRes interface {
	listOccurrencesRes()
}

type ListSoundsRes interface {
	listSoundsRes()
}

type PreviewSoundRes interface {
	previewSoundRes()
}

type SelectAudioOutputRes interface {
	selectAudioOutputRes()
}

type SetVolumeRes interface {
	setVolumeRes()
}

type SnoozeAlarmRes interface {
	snoozeAlarmRes()
}
