"""initial schema

Revision ID: 234309ce6ee1
Revises:
Create Date: 2026-08-30 15:17:14.248460

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "234309ce6ee1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Named enums are created and dropped by hand: create_table emits CREATE TYPE
# implicitly, but drop_table leaves the type behind, so a re-upgrade collides.
_ALARM_DEFECT = sa.Enum("room_missing", "scene_missing", name="alarm_defect")
_OCCURRENCE_STATE = sa.Enum(
    "pending",
    "sunrise",
    "dismissed",
    "skipped",
    "failed",
    name="occurrence_state",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alarm_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("sunrise_scene_id", sa.Uuid(), nullable=False),
        sa.Column("sunrise_scene_name", sa.String(), nullable=False),
        sa.Column("sunrise_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("sunrise_brightness_start", sa.Integer(), nullable=False),
        sa.Column("sunrise_brightness_end", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "hue_bridge_selection",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bridge_id", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("app_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bridge_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "alarms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("recurrence_mask", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("room_name", sa.String(), nullable=False),
        sa.Column(
            "defect",
            _ALARM_DEFECT,
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["alarm_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alarms_is_enabled"), "alarms", ["is_enabled"], unique=False
    )
    op.create_index(
        op.f("ix_alarms_profile_id"), "alarms", ["profile_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "alarm_occurrences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alarm_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "state",
            _OCCURRENCE_STATE,
            nullable=False,
        ),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["alarm_id"],
            ["alarms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "alarm_id", "scheduled_for", name="uq_occurrence_alarm_time"
        ),
    )
    op.create_index(
        op.f("ix_alarm_occurrences_alarm_id"),
        "alarm_occurrences",
        ["alarm_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alarm_occurrences_scheduled_for"),
        "alarm_occurrences",
        ["scheduled_for"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alarm_occurrences_state"), "alarm_occurrences", ["state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alarm_occurrences_state"), table_name="alarm_occurrences")
    op.drop_index(
        op.f("ix_alarm_occurrences_scheduled_for"), table_name="alarm_occurrences"
    )
    op.drop_index(op.f("ix_alarm_occurrences_alarm_id"), table_name="alarm_occurrences")
    op.drop_table("alarm_occurrences")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_alarms_profile_id"), table_name="alarms")
    op.drop_index(op.f("ix_alarms_is_enabled"), table_name="alarms")
    op.drop_table("alarms")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("hue_bridge_selection")
    op.drop_table("alarm_profiles")
    _OCCURRENCE_STATE.drop(op.get_bind())
    _ALARM_DEFECT.drop(op.get_bind())
    # ### end Alembic commands ###
