// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// APIKeyHeader provides APIKeyHeader security value.
	APIKeyHeader(ctx context.Context, operationName OperationName) (APIKeyHeader, error)
}

// operationRolesAPIKeyHeader is a private map storing roles per operation.
var operationRolesAPIKeyHeader = map[string][]string{
	DoctorOperation:             []string{},
	GetHueBridgeOperation:       []string{},
	ListHueBridgesOperation:     []string{},
	ListRoomsOperation:          []string{},
	ListScenesOperation:         []string{},
	RegisterHueBridgeOperation:  []string{},
	SelectHueBridgeOperation:    []string{},
	StartDaylightAlarmOperation: []string{},
	StopDaylightAlarmOperation:  []string{},
}

// GetRolesForAPIKeyHeader returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAPIKeyHeader(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAPIKeyHeader(operation string) []string {
	roles, ok := operationRolesAPIKeyHeader[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityAPIKeyHeader(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.APIKeyHeader(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"APIKeyHeader\"")
	}
	req.Header.Set("X-API-Key", t.APIKey)
	return nil
}
