// Code generated by ogen, DO NOT EDIT.

package client

// setDefaults set default value of fields.
func (s *RingtoneSchema) setDefaults() {
	{
		val := int(80)
		s.Volume.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ScheduleSchema) setDefaults() {
	{
		val := string("Europe/Berlin")
		s.Timezone.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SnoozeRequest) setDefaults() {
	{
		val := int(10)
		s.Minutes.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SoundPreviewRequest) setDefaults() {
	{
		val := int(60)
		s.Volume.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SunriseSchema) setDefaults() {
	{
		val := string("Tageslichtwecker")
		s.SceneName.SetTo(val)
	}
	{
		val := int(7)
		s.DurationMinutes.SetTo(val)
	}
	{
		val := int(1)
		s.BrightnessStart.SetTo(val)
	}
	{
		val := int(100)
		s.BrightnessEnd.SetTo(val)
	}
}
