// Code generated by ogen, DO NOT EDIT.

package client

import (
	"github.com/google/uuid"
)

// ActivateSceneParams is parameters of activate_scene operation.
type ActivateSceneParams struct {
	RoomID  uuid.UUID
	SceneID uuid.UUID
}

// DeleteAlarmParams is parameters of deleteAlarm operation.
type DeleteAlarmParams struct {
	AlarmID uuid.UUID
}

// DeleteProfileParams is parameters of deleteProfile operation.
type DeleteProfileParams struct {
	ProfileID uuid.UUID
}

// DemoSceneParams is parameters of demo_scene operation.
type DemoSceneParams struct {
	RoomID  uuid.UUID
	SceneID uuid.UUID
}

// DisableAlarmParams is parameters of disableAlarm operation.
type DisableAlarmParams struct {
	AlarmID uuid.UUID
}

// DismissAlarmParams is parameters of dismissAlarm operation.
type DismissAlarmParams struct {
	AlarmID uuid.UUID
}

// EnableAlarmParams is parameters of enableAlarm operation.
type EnableAlarmParams struct {
	AlarmID uuid.UUID
}

// GetAlarmParams is parameters of getAlarm operation.
type GetAlarmParams struct {
	AlarmID uuid.UUID
}

// GetRoomParams is parameters of get_room operation.
type GetRoomParams struct {
	RoomID uuid.UUID
}

// ListOccurrencesParams is parameters of listOccurrences operation.
type ListOccurrencesParams struct {
	AlarmID uuid.UUID
	Limit   OptInt `json:",omitempty,omitzero"`
}

// StopSceneDemoParams is parameters of stop_scene_demo operation.
type StopSceneDemoParams struct {
	RoomID  uuid.UUID
	SceneID uuid.UUID
}

// StreamEventsParams is parameters of streamEvents operation.
type StreamEventsParams struct {
	LastEventID OptString `json:",omitempty,omitzero"`
}

// UpdateAlarmParams is parameters of updateAlarm operation.
type UpdateAlarmParams struct {
	AlarmID uuid.UUID
}
