// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	DoctorOperation             OperationName = "Doctor"
	GetHueBridgeOperation       OperationName = "GetHueBridge"
	ListHueBridgesOperation     OperationName = "ListHueBridges"
	ListRoomsOperation          OperationName = "ListRooms"
	ListScenesOperation         OperationName = "ListScenes"
	RegisterHueBridgeOperation  OperationName = "RegisterHueBridge"
	SelectHueBridgeOperation    OperationName = "SelectHueBridge"
	StartDaylightAlarmOperation OperationName = "StartDaylightAlarm"
	StopDaylightAlarmOperation  OperationName = "StopDaylightAlarm"
)
