// Code generated by ogen, DO NOT EDIT.
package client

type ActivateSceneRes interface {
	activateSceneRes()
}

type CreateAlarmRes interface {
	createAlarmRes()
}

type CreateProfileRes interface {
	createProfileRes()
}

type DeleteAlarmRes interface {
	deleteAlarmRes()
}

type DeleteProfileRes interface {
	deleteProfileRes()
}

type DemoSceneRes interface {
	demoSceneRes()
}

type DisableAlarmRes interface {
	disableAlarmRes()
}

type DismissAlarmRes interface {
	dismissAlarmRes()
}

type EnableAlarmRes interface {
	enableAlarmRes()
}

type GetAlarmRes interface {
	getAlarmRes()
}

type GetRoomRes interface {
	getRoomRes()
}

type ListOccurrencesRes interface {
	listOccurrencesRes()
}

type LoginRes interface {
	loginRes()
}

type LogoutRes interface {
	logoutRes()
}

type RefreshRes interface {
	refreshRes()
}

type RegisterRes interface {
	registerRes()
}

type SelectHueBridgeRes interface {
	selectHueBridgeRes()
}

type StopSceneDemoRes interface {
	stopSceneDemoRes()
}

type StreamEventsRes interface {
	streamEventsRes()
}

type UpdateAlarmRes interface {
	updateAlarmRes()
}
