// Code generated by ogen, DO NOT EDIT.
package client

type DoctorRes interface {
	doctorRes()
}

type GetDaylightAlarmConfigurationRes interface {
	getDaylightAlarmConfigurationRes()
}

type GetHueBridgeRes interface {
	getHueBridgeRes()
}

type ListHueBridgesRes interface {
	listHueBridgesRes()
}

type ListScenesRes interface {
	listScenesRes()
}

type RegisterHueBridgeRes interface {
	registerHueBridgeRes()
}

type SelectHueBridgeRes interface {
	selectHueBridgeRes()
}

type SetDaylightAlarmConfigurationRes interface {
	setDaylightAlarmConfigurationRes()
}

type StartDaylightAlarmRes interface {
	startDaylightAlarmRes()
}
