// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// ActivateScene invokes activate_scene operation.
	//
	// Preview a scene the way an alarm would start it.
	//
	// POST /rooms/{room_name}/scenes/{scene_name}/activate
	ActivateScene(ctx context.Context, params ActivateSceneParams) (ActivateSceneRes, error)
	// CreateAlarm invokes create_alarm operation.
	//
	// Create Alarm.
	//
	// POST /alarms
	CreateAlarm(ctx context.Context, request *AlarmCreate) (CreateAlarmRes, error)
	// CreateProfile invokes createProfile operation.
	//
	// Create Profile.
	//
	// POST /alarm-profiles
	CreateProfile(ctx context.Context, request *ProfileCreate) (CreateProfileRes, error)
	// DeleteAlarm invokes deleteAlarm operation.
	//
	// Delete Alarm.
	//
	// DELETE /alarms/{alarm_id}
	DeleteAlarm(ctx context.Context, params DeleteAlarmParams) (DeleteAlarmRes, error)
	// DeleteProfile invokes deleteProfile operation.
	//
	// Delete Profile.
	//
	// DELETE /alarm-profiles/{profile_id}
	DeleteProfile(ctx context.Context, params DeleteProfileParams) (DeleteProfileRes, error)
	// DisableAlarm invokes disableAlarm operation.
	//
	// Disable Alarm.
	//
	// POST /alarms/{alarm_id}/disable
	DisableAlarm(ctx context.Context, params DisableAlarmParams) (DisableAlarmRes, error)
	// DismissAlarm invokes dismissAlarm operation.
	//
	// Dismiss Alarm.
	//
	// POST /alarms/{alarm_id}/dismiss
	DismissAlarm(ctx context.Context, params DismissAlarmParams) (DismissAlarmRes, error)
	// EnableAlarm invokes enableAlarm operation.
	//
	// Enable Alarm.
	//
	// POST /alarms/{alarm_id}/enable
	EnableAlarm(ctx context.Context, params EnableAlarmParams) (EnableAlarmRes, error)
	// GetAlarm invokes getAlarm operation.
	//
	// Get Alarm.
	//
	// GET /alarms/{alarm_id}
	GetAlarm(ctx context.Context, params GetAlarmParams) (GetAlarmRes, error)
	// GetAudioOutput invokes get_audio_output operation.
	//
	// Get Audio Output.
	//
	// GET /audio-output
	GetAudioOutput(ctx context.Context) (*AudioOutputRead, error)
	// GetRoom invokes get_room operation.
	//
	// Get Room.
	//
	// GET /rooms/{room_name}
	GetRoom(ctx context.Context, params GetRoomParams) (GetRoomRes, error)
	// ListAlarms invokes listAlarms operation.
	//
	// List Alarms.
	//
	// GET /alarms
	ListAlarms(ctx context.Context) ([]AlarmRead, error)
	// ListOccurrences invokes listOccurrences operation.
	//
	// List Occurrences.
	//
	// GET /alarms/{alarm_id}/occurrences
	ListOccurrences(ctx context.Context, params ListOccurrencesParams) (ListOccurrencesRes, error)
	// ListProfiles invokes listProfiles operation.
	//
	// List Profiles.
	//
	// GET /alarm-profiles
	ListProfiles(ctx context.Context) ([]ProfileRead, error)
	// ListRooms invokes list_rooms operation.
	//
	// List Rooms.
	//
	// GET /rooms
	ListRooms(ctx context.Context) ([]RoomRead, error)
	// ListSounds invokes list_sounds operation.
	//
	// List Sounds.
	//
	// GET /sounds
	ListSounds(ctx context.Context, params ListSoundsParams) (ListSoundsRes, error)
	// PreviewSound invokes preview_sound operation.
	//
	// Start playback and return immediately -- the sound keeps playing.
	//
	// POST /sounds/preview
	PreviewSound(ctx context.Context, request *SoundPreviewRequest) (PreviewSoundRes, error)
	// SelectAudioOutput invokes select_audio_output operation.
	//
	// Switch the output. Anything currently playing is stopped first.
	//
	// PUT /audio-output
	SelectAudioOutput(ctx context.Context, request *AudioOutputRequest) (SelectAudioOutputRes, error)
	// SetVolume invokes set_volume operation.
	//
	// Set Volume.
	//
	// POST /sounds/volume
	SetVolume(ctx context.Context, request *VolumeRequest) (SetVolumeRes, error)
	// SnoozeAlarm invokes snoozeAlarm operation.
	//
	// Snooze Alarm.
	//
	// POST /alarms/{alarm_id}/snooze
	SnoozeAlarm(ctx context.Context, request *SnoozeRequest, params SnoozeAlarmParams) (SnoozeAlarmRes, error)
	// StopPlayback invokes stop_playback operation.
	//
	// Stop Playback.
	//
	// POST /sounds/stop
	StopPlayback(ctx context.Context) error
	// StreamEvents invokes streamEvents operation.
	//
	// Server-sent events covering every change to alarms and to the run currently in
	// progress, so a display can stay in sync without polling.
	// Each frame carries the event id in `id:`, the discriminator in `event:` and the
	// event itself as JSON in `data:`. Reconnect with `Last-Event-ID` to resume; if
	// that id has rolled out of the buffer nothing is replayed, so resync over
	// `GET /alarms` first. A `: keepalive` comment arrives whenever the stream is
	// idle.
	//
	// GET /eventstream
	StreamEvents(ctx context.Context, params StreamEventsParams) (StreamEventsRes, error)
	// UpdateAlarm invokes updateAlarm operation.
	//
	// Update Alarm.
	//
	// PATCH /alarms/{alarm_id}
	UpdateAlarm(ctx context.Context, request *AlarmUpdate, params UpdateAlarmParams) (UpdateAlarmRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// ActivateScene invokes activate_scene operation.
//
// Preview a scene the way an alarm would start it.
//
// POST /rooms/{room_name}/scenes/{scene_name}/activate
func (c *Client) ActivateScene(ctx context.Context, params ActivateSceneParams) (ActivateSceneRes, error) {
	res, err := c.sendActivateScene(ctx, params)
	return res, err
}

func (c *Client) sendActivateScene(ctx context.Context, params ActivateSceneParams) (res ActivateSceneRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [5]string
	pathParts[0] = "/rooms/"
	{
		// Encode "room_name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "room_name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.RoomName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/scenes/"
	{
		// Encode "scene_name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "scene_name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.SceneName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/activate"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, ActivateSceneOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeActivateSceneResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateAlarm invokes create_alarm operation.
//
// Create Alarm.
//
// POST /alarms
func (c *Client) CreateAlarm(ctx context.Context, request *AlarmCreate) (CreateAlarmRes, error) {
	res, err := c.sendCreateAlarm(ctx, request)
	return res, err
}

func (c *Client) sendCreateAlarm(ctx context.Context, request *AlarmCreate) (res CreateAlarmRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/alarms"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateAlarmRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, CreateAlarmOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeCreateAlarmResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateProfile invokes createProfile operation.
//
// Create Profile.
//
// POST /alarm-profiles
func (c *Client) CreateProfile(ctx context.Context, request *ProfileCreate) (CreateProfileRes, error) {
	res, err := c.sendCreateProfile(ctx, request)
	return res, err
}

func (c *Client) sendCreateProfile(ctx context.Context, request *ProfileCreate) (res CreateProfileRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/alarm-profiles"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateProfileRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, CreateProfileOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeCreateProfileResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteAlarm invokes deleteAlarm operation.
//
// Delete Alarm.
//
// DELETE /alarms/{alarm_id}
func (c *Client) DeleteAlarm(ctx context.Context, params DeleteAlarmParams) (DeleteAlarmRes, error) {
	res, err := c.sendDeleteAlarm(ctx, params)
	return res, err
}

func (c *Client) sendDeleteAlarm(ctx context.Context, params DeleteAlarmParams) (res DeleteAlarmRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/alarms/"
	{
		// Encode "alarm_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "alarm_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.UUIDToString(params.AlarmID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, DeleteAlarmOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeDeleteAlarmResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteProfile invokes deleteProfile operation.
//
// Delete Profile.
//
// DELETE /alarm-profiles/{profile_id}
func (c *Client) DeleteProfile(ctx context.Context, params DeleteProfileParams) (DeleteProfileRes, error) {
	res, err := c.sendDeleteProfile(ctx, params)
	return res, err
}

func (c *Client) sendDeleteProfile(ctx context.Context, params DeleteProfileParams) (res DeleteProfileRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/alarm-profiles/"
	{
		// Encode "profile_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "profile_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.UUIDToString(params.ProfileID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, DeleteProfileOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeDeleteProfileResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DisableAlarm invokes disableAlarm operation.
//
// Disable Alarm.
//
// POST /alarms/{alarm_id}/disable
func (c *Client) DisableAlarm(ctx context.Context, params DisableAlarmParams) (DisableAlarmRes, error) {
	res, err := c.sendDisableAlarm(ctx, params)
	return res, err
}

func (c *Client) sendDisableAlarm(ctx context.Context, params DisableAlarmParams) (res DisableAlarmRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/alarms/"
	{
		// Encode "alarm_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "alarm_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.UUIDToString(params.AlarmID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/disable"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, DisableAlarmOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeDisableAlarmResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DismissAlarm invokes dismissAlarm operation.
//
// Dismiss Alarm.
//
// POST /alarms/{alarm_id}/dismiss
func (c *Client) DismissAlarm(ctx context.Context, params DismissAlarmParams) (DismissAlarmRes, error) {
	res, err := c.sendDismissAlarm(ctx, params)
	return res, err
}

func (c *Client) sendDismissAlarm(ctx context.Context, params DismissAlarmParams) (res DismissAlarmRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/alarms/"
	{
		// Encode "alarm_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "alarm_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.UUIDToString(params.AlarmID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/dismiss"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, DismissAlarmOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeDismissAlarmResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// EnableAlarm invokes enableAlarm operation.
//
// Enable Alarm.
//
// POST /alarms/{alarm_id}/enable
func (c *Client) EnableAlarm(ctx context.Context, params EnableAlarmParams) (EnableAlarmRes, error) {
	res, err := c.sendEnableAlarm(ctx, params)
	return res, err
}

func (c *Client) sendEnableAlarm(ctx context.Context, params EnableAlarmParams) (res EnableAlarmRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/alarms/"
	{
		// Encode "alarm_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "alarm_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.UUIDToString(params.AlarmID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/enable"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, EnableAlarmOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeEnableAlarmResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetAlarm invokes getAlarm operation.
//
// Get Alarm.
//
// GET /alarms/{alarm_id}
func (c *Client) GetAlarm(ctx context.Context, params GetAlarmParams) (GetAlarmRes, error) {
	res, err := c.sendGetAlarm(ctx, params)
	return res, err
}

func (c *Client) sendGetAlarm(ctx context.Context, params GetAlarmParams) (res GetAlarmRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/alarms/"
	{
		// Encode "alarm_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "alarm_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.UUIDToString(params.AlarmID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, GetAlarmOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeGetAlarmResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetAudioOutput invokes get_audio_output operation.
//
// Get Audio Output.
//
// GET /audio-output
func (c *Client) GetAudioOutput(ctx context.Context) (*AudioOutputRead, error) {
	res, err := c.sendGetAudioOutput(ctx)
	return res, err
}

func (c *Client) sendGetAudioOutput(ctx context.Context) (res *AudioOutputRead, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/audio-output"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, GetAudioOutputOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeGetAudioOutputResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetRoom invokes get_room operation.
//
// Get Room.
//
// GET /rooms/{room_name}
func (c *Client) GetRoom(ctx context.Context, params GetRoomParams) (GetRoomRes, error) {
	res, err := c.sendGetRoom(ctx, params)
	return res, err
}

func (c *Client) sendGetRoom(ctx context.Context, params GetRoomParams) (res GetRoomRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/rooms/"
	{
		// Encode "room_name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "room_name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.RoomName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, GetRoomOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeGetRoomResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListAlarms invokes listAlarms operation.
//
// List Alarms.
//
// GET /alarms
func (c *Client) ListAlarms(ctx context.Context) ([]AlarmRead, error) {
	res, err := c.sendListAlarms(ctx)
	return res, err
}

func (c *Client) sendListAlarms(ctx context.Context) (res []AlarmRead, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/alarms"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, ListAlarmsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeListAlarmsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListOccurrences invokes listOccurrences operation.
//
// List Occurrences.
//
// GET /alarms/{alarm_id}/occurrences
func (c *Client) ListOccurrences(ctx context.Context, params ListOccurrencesParams) (ListOccurrencesRes, error) {
	res, err := c.sendListOccurrences(ctx, params)
	return res, err
}

func (c *Client) sendListOccurrences(ctx context.Context, params ListOccurrencesParams) (res ListOccurrencesRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/alarms/"
	{
		// Encode "alarm_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "alarm_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.UUIDToString(params.AlarmID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/occurrences"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, ListOccurrencesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeListOccurrencesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListProfiles invokes listProfiles operation.
//
// List Profiles.
//
// GET /alarm-profiles
func (c *Client) ListProfiles(ctx context.Context) ([]ProfileRead, error) {
	res, err := c.sendListProfiles(ctx)
	return res, err
}

func (c *Client) sendListProfiles(ctx context.Context) (res []ProfileRead, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/alarm-profiles"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, ListProfilesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeListProfilesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListRooms invokes list_rooms operation.
//
// List Rooms.
//
// GET /rooms
func (c *Client) ListRooms(ctx context.Context) ([]RoomRead, error) {
	res, err := c.sendListRooms(ctx)
	return res, err
}

func (c *Client) sendListRooms(ctx context.Context) (res []RoomRead, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/rooms"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, ListRoomsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeListRoomsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListSounds invokes list_sounds operation.
//
// List Sounds.
//
// GET /sounds
func (c *Client) ListSounds(ctx context.Context, params ListSoundsParams) (ListSoundsRes, error) {
	res, err := c.sendListSounds(ctx, params)
	return res, err
}

func (c *Client) sendListSounds(ctx context.Context, params ListSoundsParams) (res ListSoundsRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/sounds"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "category" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "category",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Category.Get(); ok {
				return e.EncodeValue(conv.StringToString(string(val)))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, ListSoundsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeListSoundsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// PreviewSound invokes preview_sound operation.
//
// Start playback and return immediately -- the sound keeps playing.
//
// POST /sounds/preview
func (c *Client) PreviewSound(ctx context.Context, request *SoundPreviewRequest) (PreviewSoundRes, error) {
	res, err := c.sendPreviewSound(ctx, request)
	return res, err
}

func (c *Client) sendPreviewSound(ctx context.Context, request *SoundPreviewRequest) (res PreviewSoundRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/sounds/preview"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodePreviewSoundRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, PreviewSoundOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodePreviewSoundResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SelectAudioOutput invokes select_audio_output operation.
//
// Switch the output. Anything currently playing is stopped first.
//
// PUT /audio-output
func (c *Client) SelectAudioOutput(ctx context.Context, request *AudioOutputRequest) (SelectAudioOutputRes, error) {
	res, err := c.sendSelectAudioOutput(ctx, request)
	return res, err
}

func (c *Client) sendSelectAudioOutput(ctx context.Context, request *AudioOutputRequest) (res SelectAudioOutputRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/audio-output"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSelectAudioOutputRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, SelectAudioOutputOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSelectAudioOutputResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SetVolume invokes set_volume operation.
//
// Set Volume.
//
// POST /sounds/volume
func (c *Client) SetVolume(ctx context.Context, request *VolumeRequest) (SetVolumeRes, error) {
	res, err := c.sendSetVolume(ctx, request)
	return res, err
}

func (c *Client) sendSetVolume(ctx context.Context, request *VolumeRequest) (res SetVolumeRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/sounds/volume"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSetVolumeRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, SetVolumeOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSetVolumeResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SnoozeAlarm invokes snoozeAlarm operation.
//
// Snooze Alarm.
//
// POST /alarms/{alarm_id}/snooze
func (c *Client) SnoozeAlarm(ctx context.Context, request *SnoozeRequest, params SnoozeAlarmParams) (SnoozeAlarmRes, error) {
	res, err := c.sendSnoozeAlarm(ctx, request, params)
	return res, err
}

func (c *Client) sendSnoozeAlarm(ctx context.Context, request *SnoozeRequest, params SnoozeAlarmParams) (res SnoozeAlarmRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/alarms/"
	{
		// Encode "alarm_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "alarm_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.UUIDToString(params.AlarmID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/snooze"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSnoozeAlarmRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, SnoozeAlarmOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSnoozeAlarmResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// StopPlayback invokes stop_playback operation.
//
// Stop Playback.
//
// POST /sounds/stop
func (c *Client) StopPlayback(ctx context.Context) error {
	_, err := c.sendStopPlayback(ctx)
	return err
}

func (c *Client) sendStopPlayback(ctx context.Context) (res *StopPlaybackNoContent, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/sounds/stop"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, StopPlaybackOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeStopPlaybackResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// StreamEvents invokes streamEvents operation.
//
// Server-sent events covering every change to alarms and to the run currently in
// progress, so a display can stay in sync without polling.
// Each frame carries the event id in `id:`, the discriminator in `event:` and the
// event itself as JSON in `data:`. Reconnect with `Last-Event-ID` to resume; if
// that id has rolled out of the buffer nothing is replayed, so resync over
// `GET /alarms` first. A `: keepalive` comment arrives whenever the stream is
// idle.
//
// GET /eventstream
func (c *Client) StreamEvents(ctx context.Context, params StreamEventsParams) (StreamEventsRes, error) {
	res, err := c.sendStreamEvents(ctx, params)
	return res, err
}

func (c *Client) sendStreamEvents(ctx context.Context, params StreamEventsParams) (res StreamEventsRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/eventstream"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "Last-Event-ID",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.LastEventID.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, StreamEventsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeStreamEventsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UpdateAlarm invokes updateAlarm operation.
//
// Update Alarm.
//
// PATCH /alarms/{alarm_id}
func (c *Client) UpdateAlarm(ctx context.Context, request *AlarmUpdate, params UpdateAlarmParams) (UpdateAlarmRes, error) {
	res, err := c.sendUpdateAlarm(ctx, request, params)
	return res, err
}

func (c *Client) sendUpdateAlarm(ctx context.Context, request *AlarmUpdate, params UpdateAlarmParams) (res UpdateAlarmRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/alarms/"
	{
		// Encode "alarm_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "alarm_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.UUIDToString(params.AlarmID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PATCH", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUpdateAlarmRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, UpdateAlarmOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeUpdateAlarmResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
