// Code generated by ogen, DO NOT EDIT.

package client

// setDefaults set default value of fields.
func (s *AlarmStatusResponse) setDefaults() {
	{
		val := string("started")
		s.Status.SetTo(val)
	}
}
