// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	ActivateSceneOperation      OperationName = "ActivateScene"
	CreateAlarmOperation        OperationName = "CreateAlarm"
	CreateProfileOperation      OperationName = "CreateProfile"
	DeleteAlarmOperation        OperationName = "DeleteAlarm"
	DeleteProfileOperation      OperationName = "DeleteProfile"
	DemoSceneOperation          OperationName = "DemoScene"
	DisableAlarmOperation       OperationName = "DisableAlarm"
	DismissAlarmOperation       OperationName = "DismissAlarm"
	DoctorOperation             OperationName = "Doctor"
	EnableAlarmOperation        OperationName = "EnableAlarm"
	GetAlarmOperation           OperationName = "GetAlarm"
	GetAudioOutputOperation     OperationName = "GetAudioOutput"
	GetHueBridgeOperation       OperationName = "GetHueBridge"
	GetRoomOperation            OperationName = "GetRoom"
	HealthOperation             OperationName = "Health"
	ListAlarmsOperation         OperationName = "ListAlarms"
	ListHueBridgesOperation     OperationName = "ListHueBridges"
	ListOccurrencesOperation    OperationName = "ListOccurrences"
	ListProfilesOperation       OperationName = "ListProfiles"
	ListRoomsOperation          OperationName = "ListRooms"
	ListSonosSpeakersOperation  OperationName = "ListSonosSpeakers"
	ListSoundsOperation         OperationName = "ListSounds"
	PreviewSoundOperation       OperationName = "PreviewSound"
	ReadinessOperation          OperationName = "Readiness"
	RegisterHueBridgeOperation  OperationName = "RegisterHueBridge"
	SelectAudioOutputOperation  OperationName = "SelectAudioOutput"
	SelectHueBridgeOperation    OperationName = "SelectHueBridge"
	SelectSonosSpeakerOperation OperationName = "SelectSonosSpeaker"
	SetVolumeOperation          OperationName = "SetVolume"
	SnoozeAlarmOperation        OperationName = "SnoozeAlarm"
	StopPlaybackOperation       OperationName = "StopPlayback"
	StopSceneDemoOperation      OperationName = "StopSceneDemo"
	StreamEventsOperation       OperationName = "StreamEvents"
	UpdateAlarmOperation        OperationName = "UpdateAlarm"
)
