// Code generated by ogen, DO NOT EDIT.

package client

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type APIKeyHeader struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *APIKeyHeader) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *APIKeyHeader) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *APIKeyHeader) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *APIKeyHeader) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/AfterAlarmConfigurationRequest
type AfterAlarmConfigurationRequest struct {
	RoomID       uuid.UUID `json:"room_id"`
	SceneID      uuid.UUID `json:"scene_id"`
	DelaySeconds int       `json:"delay_seconds"`
}

// GetRoomID returns the value of RoomID.
func (s *AfterAlarmConfigurationRequest) GetRoomID() uuid.UUID {
	return s.RoomID
}

// GetSceneID returns the value of SceneID.
func (s *AfterAlarmConfigurationRequest) GetSceneID() uuid.UUID {
	return s.SceneID
}

// GetDelaySeconds returns the value of DelaySeconds.
func (s *AfterAlarmConfigurationRequest) GetDelaySeconds() int {
	return s.DelaySeconds
}

// SetRoomID sets the value of RoomID.
func (s *AfterAlarmConfigurationRequest) SetRoomID(val uuid.UUID) {
	s.RoomID = val
}

// SetSceneID sets the value of SceneID.
func (s *AfterAlarmConfigurationRequest) SetSceneID(val uuid.UUID) {
	s.SceneID = val
}

// SetDelaySeconds sets the value of DelaySeconds.
func (s *AfterAlarmConfigurationRequest) SetDelaySeconds(val int) {
	s.DelaySeconds = val
}

// Ref: #/components/schemas/AfterAlarmConfigurationResponse
type AfterAlarmConfigurationResponse struct {
	Room         NamedResourceResponse `json:"room"`
	Scene        NamedResourceResponse `json:"scene"`
	DelaySeconds int                   `json:"delay_seconds"`
}

// GetRoom returns the value of Room.
func (s *AfterAlarmConfigurationResponse) GetRoom() NamedResourceResponse {
	return s.Room
}

// GetScene returns the value of Scene.
func (s *AfterAlarmConfigurationResponse) GetScene() NamedResourceResponse {
	return s.Scene
}

// GetDelaySeconds returns the value of DelaySeconds.
func (s *AfterAlarmConfigurationResponse) GetDelaySeconds() int {
	return s.DelaySeconds
}

// SetRoom sets the value of Room.
func (s *AfterAlarmConfigurationResponse) SetRoom(val NamedResourceResponse) {
	s.Room = val
}

// SetScene sets the value of Scene.
func (s *AfterAlarmConfigurationResponse) SetScene(val NamedResourceResponse) {
	s.Scene = val
}

// SetDelaySeconds sets the value of DelaySeconds.
func (s *AfterAlarmConfigurationResponse) SetDelaySeconds(val int) {
	s.DelaySeconds = val
}

// Ref: #/components/schemas/AlarmStatusResponse
type AlarmStatusResponse struct {
	Status          OptString `json:"status"`
	DurationSeconds int       `json:"duration_seconds"`
}

// GetStatus returns the value of Status.
func (s *AlarmStatusResponse) GetStatus() OptString {
	return s.Status
}

// GetDurationSeconds returns the value of DurationSeconds.
func (s *AlarmStatusResponse) GetDurationSeconds() int {
	return s.DurationSeconds
}

// SetStatus sets the value of Status.
func (s *AlarmStatusResponse) SetStatus(val OptString) {
	s.Status = val
}

// SetDurationSeconds sets the value of DurationSeconds.
func (s *AlarmStatusResponse) SetDurationSeconds(val int) {
	s.DurationSeconds = val
}

func (*AlarmStatusResponse) startDaylightAlarmRes() {}

// Ref: #/components/schemas/AvailableSceneResponse
type AvailableSceneResponse struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	RoomID     uuid.UUID  `json:"room_id"`
	RoomName   string     `json:"room_name"`
	Brightness NilFloat64 `json:"brightness"`
}

// GetID returns the value of ID.
func (s *AvailableSceneResponse) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *AvailableSceneResponse) GetName() string {
	return s.Name
}

// GetRoomID returns the value of RoomID.
func (s *AvailableSceneResponse) GetRoomID() uuid.UUID {
	return s.RoomID
}

// GetRoomName returns the value of RoomName.
func (s *AvailableSceneResponse) GetRoomName() string {
	return s.RoomName
}

// GetBrightness returns the value of Brightness.
func (s *AvailableSceneResponse) GetBrightness() NilFloat64 {
	return s.Brightness
}

// SetID sets the value of ID.
func (s *AvailableSceneResponse) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *AvailableSceneResponse) SetName(val string) {
	s.Name = val
}

// SetRoomID sets the value of RoomID.
func (s *AvailableSceneResponse) SetRoomID(val uuid.UUID) {
	s.RoomID = val
}

// SetRoomName sets the value of RoomName.
func (s *AvailableSceneResponse) SetRoomName(val string) {
	s.RoomName = val
}

// SetBrightness sets the value of Brightness.
func (s *AvailableSceneResponse) SetBrightness(val NilFloat64) {
	s.Brightness = val
}

// Ref: #/components/schemas/BridgeResponse
type BridgeResponse struct {
	ID        string `json:"id"`
	IPAddress string `json:"ip_address"`
	Selected  bool   `json:"selected"`
}

// GetID returns the value of ID.
func (s *BridgeResponse) GetID() string {
	return s.ID
}

// GetIPAddress returns the value of IPAddress.
func (s *BridgeResponse) GetIPAddress() string {
	return s.IPAddress
}

// GetSelected returns the value of Selected.
func (s *BridgeResponse) GetSelected() bool {
	return s.Selected
}

// SetID sets the value of ID.
func (s *BridgeResponse) SetID(val string) {
	s.ID = val
}

// SetIPAddress sets the value of IPAddress.
func (s *BridgeResponse) SetIPAddress(val string) {
	s.IPAddress = val
}

// SetSelected sets the value of Selected.
func (s *BridgeResponse) SetSelected(val bool) {
	s.Selected = val
}

// Ref: #/components/schemas/BridgeSelectionRequest
type BridgeSelectionRequest struct {
	BridgeID string `json:"bridge_id"`
}

// GetBridgeID returns the value of BridgeID.
func (s *BridgeSelectionRequest) GetBridgeID() string {
	return s.BridgeID
}

// SetBridgeID sets the value of BridgeID.
func (s *BridgeSelectionRequest) SetBridgeID(val string) {
	s.BridgeID = val
}

// Ref: #/components/schemas/ConfigurationErrorResponse
type ConfigurationErrorResponse struct {
	Detail string               `json:"detail"`
	Issues []ConfigurationIssue `json:"issues"`
}

// GetDetail returns the value of Detail.
func (s *ConfigurationErrorResponse) GetDetail() string {
	return s.Detail
}

// GetIssues returns the value of Issues.
func (s *ConfigurationErrorResponse) GetIssues() []ConfigurationIssue {
	return s.Issues
}

// SetDetail sets the value of Detail.
func (s *ConfigurationErrorResponse) SetDetail(val string) {
	s.Detail = val
}

// SetIssues sets the value of Issues.
func (s *ConfigurationErrorResponse) SetIssues(val []ConfigurationIssue) {
	s.Issues = val
}

func (*ConfigurationErrorResponse) doctorRes()             {}
func (*ConfigurationErrorResponse) getHueBridgeRes()       {}
func (*ConfigurationErrorResponse) listHueBridgesRes()     {}
func (*ConfigurationErrorResponse) listScenesRes()         {}
func (*ConfigurationErrorResponse) registerHueBridgeRes()  {}
func (*ConfigurationErrorResponse) selectHueBridgeRes()    {}
func (*ConfigurationErrorResponse) startDaylightAlarmRes() {}

// Ref: #/components/schemas/ConfigurationIssue
type ConfigurationIssue struct {
	Location string `json:"location"`
	Message  string `json:"message"`
	Type     string `json:"type"`
}

// GetLocation returns the value of Location.
func (s *ConfigurationIssue) GetLocation() string {
	return s.Location
}

// GetMessage returns the value of Message.
func (s *ConfigurationIssue) GetMessage() string {
	return s.Message
}

// GetType returns the value of Type.
func (s *ConfigurationIssue) GetType() string {
	return s.Type
}

// SetLocation sets the value of Location.
func (s *ConfigurationIssue) SetLocation(val string) {
	s.Location = val
}

// SetMessage sets the value of Message.
func (s *ConfigurationIssue) SetMessage(val string) {
	s.Message = val
}

// SetType sets the value of Type.
func (s *ConfigurationIssue) SetType(val string) {
	s.Type = val
}

// Ref: #/components/schemas/DaylightAlarmConfigurationRequest
type DaylightAlarmConfigurationRequest struct {
	RoomID          uuid.UUID                            `json:"room_id"`
	SceneID         uuid.UUID                            `json:"scene_id"`
	DurationSeconds int                                  `json:"duration_seconds"`
	AfterAlarm      OptNilAfterAlarmConfigurationRequest `json:"after_alarm"`
}

// GetRoomID returns the value of RoomID.
func (s *DaylightAlarmConfigurationRequest) GetRoomID() uuid.UUID {
	return s.RoomID
}

// GetSceneID returns the value of SceneID.
func (s *DaylightAlarmConfigurationRequest) GetSceneID() uuid.UUID {
	return s.SceneID
}

// GetDurationSeconds returns the value of DurationSeconds.
func (s *DaylightAlarmConfigurationRequest) GetDurationSeconds() int {
	return s.DurationSeconds
}

// GetAfterAlarm returns the value of AfterAlarm.
func (s *DaylightAlarmConfigurationRequest) GetAfterAlarm() OptNilAfterAlarmConfigurationRequest {
	return s.AfterAlarm
}

// SetRoomID sets the value of RoomID.
func (s *DaylightAlarmConfigurationRequest) SetRoomID(val uuid.UUID) {
	s.RoomID = val
}

// SetSceneID sets the value of SceneID.
func (s *DaylightAlarmConfigurationRequest) SetSceneID(val uuid.UUID) {
	s.SceneID = val
}

// SetDurationSeconds sets the value of DurationSeconds.
func (s *DaylightAlarmConfigurationRequest) SetDurationSeconds(val int) {
	s.DurationSeconds = val
}

// SetAfterAlarm sets the value of AfterAlarm.
func (s *DaylightAlarmConfigurationRequest) SetAfterAlarm(val OptNilAfterAlarmConfigurationRequest) {
	s.AfterAlarm = val
}

// Ref: #/components/schemas/DaylightAlarmConfigurationResponse
type DaylightAlarmConfigurationResponse struct {
	Room            NamedResourceResponse                 `json:"room"`
	Scene           NamedResourceResponse                 `json:"scene"`
	DurationSeconds int                                   `json:"duration_seconds"`
	AfterAlarm      OptNilAfterAlarmConfigurationResponse `json:"after_alarm"`
}

// GetRoom returns the value of Room.
func (s *DaylightAlarmConfigurationResponse) GetRoom() NamedResourceResponse {
	return s.Room
}

// GetScene returns the value of Scene.
func (s *DaylightAlarmConfigurationResponse) GetScene() NamedResourceResponse {
	return s.Scene
}

// GetDurationSeconds returns the value of DurationSeconds.
func (s *DaylightAlarmConfigurationResponse) GetDurationSeconds() int {
	return s.DurationSeconds
}

// GetAfterAlarm returns the value of AfterAlarm.
func (s *DaylightAlarmConfigurationResponse) GetAfterAlarm() OptNilAfterAlarmConfigurationResponse {
	return s.AfterAlarm
}

// SetRoom sets the value of Room.
func (s *DaylightAlarmConfigurationResponse) SetRoom(val NamedResourceResponse) {
	s.Room = val
}

// SetScene sets the value of Scene.
func (s *DaylightAlarmConfigurationResponse) SetScene(val NamedResourceResponse) {
	s.Scene = val
}

// SetDurationSeconds sets the value of DurationSeconds.
func (s *DaylightAlarmConfigurationResponse) SetDurationSeconds(val int) {
	s.DurationSeconds = val
}

// SetAfterAlarm sets the value of AfterAlarm.
func (s *DaylightAlarmConfigurationResponse) SetAfterAlarm(val OptNilAfterAlarmConfigurationResponse) {
	s.AfterAlarm = val
}

func (*DaylightAlarmConfigurationResponse) getDaylightAlarmConfigurationRes() {}
func (*DaylightAlarmConfigurationResponse) setDaylightAlarmConfigurationRes() {}

// Ref: #/components/schemas/DoctorCheckResponse
type DoctorCheckResponse struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

// GetName returns the value of Name.
func (s *DoctorCheckResponse) GetName() string {
	return s.Name
}

// GetStatus returns the value of Status.
func (s *DoctorCheckResponse) GetStatus() string {
	return s.Status
}

// SetName sets the value of Name.
func (s *DoctorCheckResponse) SetName(val string) {
	s.Name = val
}

// SetStatus sets the value of Status.
func (s *DoctorCheckResponse) SetStatus(val string) {
	s.Status = val
}

type DoctorNotFound ErrorResponse

func (*DoctorNotFound) doctorRes() {}

// Ref: #/components/schemas/DoctorResponse
type DoctorResponse struct {
	Status string                `json:"status"`
	Checks []DoctorCheckResponse `json:"checks"`
}

// GetStatus returns the value of Status.
func (s *DoctorResponse) GetStatus() string {
	return s.Status
}

// GetChecks returns the value of Checks.
func (s *DoctorResponse) GetChecks() []DoctorCheckResponse {
	return s.Checks
}

// SetStatus sets the value of Status.
func (s *DoctorResponse) SetStatus(val string) {
	s.Status = val
}

// SetChecks sets the value of Checks.
func (s *DoctorResponse) SetChecks(val []DoctorCheckResponse) {
	s.Checks = val
}

func (*DoctorResponse) doctorRes() {}

type DoctorServiceUnavailable ErrorResponse

func (*DoctorServiceUnavailable) doctorRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Detail string `json:"detail"`
}

// GetDetail returns the value of Detail.
func (s *ErrorResponse) GetDetail() string {
	return s.Detail
}

// SetDetail sets the value of Detail.
func (s *ErrorResponse) SetDetail(val string) {
	s.Detail = val
}

func (*ErrorResponse) listHueBridgesRes() {}
func (*ErrorResponse) listScenesRes()     {}

type GetDaylightAlarmConfigurationNotFound ErrorResponse

func (*GetDaylightAlarmConfigurationNotFound) getDaylightAlarmConfigurationRes() {}

type GetDaylightAlarmConfigurationServiceUnavailable ErrorResponse

func (*GetDaylightAlarmConfigurationServiceUnavailable) getDaylightAlarmConfigurationRes() {}

type GetDaylightAlarmConfigurationUnprocessableEntity ErrorResponse

func (*GetDaylightAlarmConfigurationUnprocessableEntity) getDaylightAlarmConfigurationRes() {}

type ListHueBridgesOKApplicationJSON []BridgeResponse

func (*ListHueBridgesOKApplicationJSON) listHueBridgesRes() {}

type ListScenesOKApplicationJSON []AvailableSceneResponse

func (*ListScenesOKApplicationJSON) listScenesRes() {}

// Ref: #/components/schemas/NamedResourceResponse
type NamedResourceResponse struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// GetID returns the value of ID.
func (s *NamedResourceResponse) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *NamedResourceResponse) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *NamedResourceResponse) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *NamedResourceResponse) SetName(val string) {
	s.Name = val
}

// NewNilFloat64 returns new NilFloat64 with value set to v.
func NewNilFloat64(v float64) NilFloat64 {
	return NilFloat64{
		Value: v,
	}
}

// NilFloat64 is nullable float64.
type NilFloat64 struct {
	Value float64
	Null  bool
}

// SetTo sets value to v.
func (o *NilFloat64) SetTo(v float64) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilFloat64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilFloat64) SetToNull() {
	o.Null = true
	var v float64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilFloat64) Get() (v float64, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OnboardingState
type OnboardingState string

const (
	OnboardingStateNotSelected        OnboardingState = "not_selected"
	OnboardingStateLinkButtonRequired OnboardingState = "link_button_required"
	OnboardingStateReady              OnboardingState = "ready"
)

// AllValues returns all OnboardingState values.
func (OnboardingState) AllValues() []OnboardingState {
	return []OnboardingState{
		OnboardingStateNotSelected,
		OnboardingStateLinkButtonRequired,
		OnboardingStateReady,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OnboardingState) MarshalText() ([]byte, error) {
	switch s {
	case OnboardingStateNotSelected:
		return []byte(s), nil
	case OnboardingStateLinkButtonRequired:
		return []byte(s), nil
	case OnboardingStateReady:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OnboardingState) UnmarshalText(data []byte) error {
	switch OnboardingState(data) {
	case OnboardingStateNotSelected:
		*s = OnboardingStateNotSelected
		return nil
	case OnboardingStateLinkButtonRequired:
		*s = OnboardingStateLinkButtonRequired
		return nil
	case OnboardingStateReady:
		*s = OnboardingStateReady
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/OnboardingStatusResponse
type OnboardingStatusResponse struct {
	State     OnboardingState `json:"state"`
	BridgeID  NilString       `json:"bridge_id"`
	IPAddress NilString       `json:"ip_address"`
	ReadOnly  bool            `json:"read_only"`
}

// GetState returns the value of State.
func (s *OnboardingStatusResponse) GetState() OnboardingState {
	return s.State
}

// GetBridgeID returns the value of BridgeID.
func (s *OnboardingStatusResponse) GetBridgeID() NilString {
	return s.BridgeID
}

// GetIPAddress returns the value of IPAddress.
func (s *OnboardingStatusResponse) GetIPAddress() NilString {
	return s.IPAddress
}

// GetReadOnly returns the value of ReadOnly.
func (s *OnboardingStatusResponse) GetReadOnly() bool {
	return s.ReadOnly
}

// SetState sets the value of State.
func (s *OnboardingStatusResponse) SetState(val OnboardingState) {
	s.State = val
}

// SetBridgeID sets the value of BridgeID.
func (s *OnboardingStatusResponse) SetBridgeID(val NilString) {
	s.BridgeID = val
}

// SetIPAddress sets the value of IPAddress.
func (s *OnboardingStatusResponse) SetIPAddress(val NilString) {
	s.IPAddress = val
}

// SetReadOnly sets the value of ReadOnly.
func (s *OnboardingStatusResponse) SetReadOnly(val bool) {
	s.ReadOnly = val
}

func (*OnboardingStatusResponse) getHueBridgeRes()      {}
func (*OnboardingStatusResponse) registerHueBridgeRes() {}
func (*OnboardingStatusResponse) selectHueBridgeRes()   {}

// NewOptNilAfterAlarmConfigurationRequest returns new OptNilAfterAlarmConfigurationRequest with value set to v.
func NewOptNilAfterAlarmConfigurationRequest(v AfterAlarmConfigurationRequest) OptNilAfterAlarmConfigurationRequest {
	return OptNilAfterAlarmConfigurationRequest{
		Value: v,
		Set:   true,
	}
}

// OptNilAfterAlarmConfigurationRequest is optional nullable AfterAlarmConfigurationRequest.
type OptNilAfterAlarmConfigurationRequest struct {
	Value AfterAlarmConfigurationRequest
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilAfterAlarmConfigurationRequest was set.
func (o OptNilAfterAlarmConfigurationRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilAfterAlarmConfigurationRequest) Reset() {
	var v AfterAlarmConfigurationRequest
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilAfterAlarmConfigurationRequest) SetTo(v AfterAlarmConfigurationRequest) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilAfterAlarmConfigurationRequest) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilAfterAlarmConfigurationRequest) SetToNull() {
	o.Set = true
	o.Null = true
	var v AfterAlarmConfigurationRequest
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilAfterAlarmConfigurationRequest) Get() (v AfterAlarmConfigurationRequest, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilAfterAlarmConfigurationRequest) Or(d AfterAlarmConfigurationRequest) AfterAlarmConfigurationRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilAfterAlarmConfigurationResponse returns new OptNilAfterAlarmConfigurationResponse with value set to v.
func NewOptNilAfterAlarmConfigurationResponse(v AfterAlarmConfigurationResponse) OptNilAfterAlarmConfigurationResponse {
	return OptNilAfterAlarmConfigurationResponse{
		Value: v,
		Set:   true,
	}
}

// OptNilAfterAlarmConfigurationResponse is optional nullable AfterAlarmConfigurationResponse.
type OptNilAfterAlarmConfigurationResponse struct {
	Value AfterAlarmConfigurationResponse
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilAfterAlarmConfigurationResponse was set.
func (o OptNilAfterAlarmConfigurationResponse) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilAfterAlarmConfigurationResponse) Reset() {
	var v AfterAlarmConfigurationResponse
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilAfterAlarmConfigurationResponse) SetTo(v AfterAlarmConfigurationResponse) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilAfterAlarmConfigurationResponse) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilAfterAlarmConfigurationResponse) SetToNull() {
	o.Set = true
	o.Null = true
	var v AfterAlarmConfigurationResponse
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilAfterAlarmConfigurationResponse) Get() (v AfterAlarmConfigurationResponse, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilAfterAlarmConfigurationResponse) Or(d AfterAlarmConfigurationResponse) AfterAlarmConfigurationResponse {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilStartRequest returns new OptNilStartRequest with value set to v.
func NewOptNilStartRequest(v StartRequest) OptNilStartRequest {
	return OptNilStartRequest{
		Value: v,
		Set:   true,
	}
}

// OptNilStartRequest is optional nullable StartRequest.
type OptNilStartRequest struct {
	Value StartRequest
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilStartRequest was set.
func (o OptNilStartRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilStartRequest) Reset() {
	var v StartRequest
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilStartRequest) SetTo(v StartRequest) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilStartRequest) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilStartRequest) SetToNull() {
	o.Set = true
	o.Null = true
	var v StartRequest
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilStartRequest) Get() (v StartRequest, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilStartRequest) Or(d StartRequest) StartRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RegisterHueBridgeConflict ErrorResponse

func (*RegisterHueBridgeConflict) registerHueBridgeRes() {}

type RegisterHueBridgeServiceUnavailable ErrorResponse

func (*RegisterHueBridgeServiceUnavailable) registerHueBridgeRes() {}

type SelectHueBridgeConflict ErrorResponse

func (*SelectHueBridgeConflict) selectHueBridgeRes() {}

type SelectHueBridgeNotFound ErrorResponse

func (*SelectHueBridgeNotFound) selectHueBridgeRes() {}

type SelectHueBridgeServiceUnavailable ErrorResponse

func (*SelectHueBridgeServiceUnavailable) selectHueBridgeRes() {}

type SetDaylightAlarmConfigurationNotFound ErrorResponse

func (*SetDaylightAlarmConfigurationNotFound) setDaylightAlarmConfigurationRes() {}

type SetDaylightAlarmConfigurationServiceUnavailable ErrorResponse

func (*SetDaylightAlarmConfigurationServiceUnavailable) setDaylightAlarmConfigurationRes() {}

type SetDaylightAlarmConfigurationUnprocessableEntity ErrorResponse

func (*SetDaylightAlarmConfigurationUnprocessableEntity) setDaylightAlarmConfigurationRes() {}

type StartDaylightAlarmConflict ErrorResponse

func (*StartDaylightAlarmConflict) startDaylightAlarmRes() {}

type StartDaylightAlarmNotFound ErrorResponse

func (*StartDaylightAlarmNotFound) startDaylightAlarmRes() {}

type StartDaylightAlarmServiceUnavailable ErrorResponse

func (*StartDaylightAlarmServiceUnavailable) startDaylightAlarmRes() {}

// Ref: #/components/schemas/StartRequest
type StartRequest struct {
	DurationSeconds int `json:"duration_seconds"`
}

// GetDurationSeconds returns the value of DurationSeconds.
func (s *StartRequest) GetDurationSeconds() int {
	return s.DurationSeconds
}

// SetDurationSeconds sets the value of DurationSeconds.
func (s *StartRequest) SetDurationSeconds(val int) {
	s.DurationSeconds = val
}

// StopDaylightAlarmNoContent is response for StopDaylightAlarm operation.
type StopDaylightAlarmNoContent struct{}
