// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AccessToken provides AccessToken security value.
	// Send the API access token as `Authorization: Bearer <token>`.
	AccessToken(ctx context.Context, operationName OperationName) (AccessToken, error)
}

// operationRolesAccessToken is a private map storing roles per operation.
var operationRolesAccessToken = map[string][]string{
	ActivateSceneOperation:     []string{},
	CreateAlarmOperation:       []string{},
	CreateProfileOperation:     []string{},
	DeleteAlarmOperation:       []string{},
	DeleteProfileOperation:     []string{},
	DisableAlarmOperation:      []string{},
	DismissAlarmOperation:      []string{},
	EnableAlarmOperation:       []string{},
	GetAlarmOperation:          []string{},
	GetAudioOutputOperation:    []string{},
	GetRoomOperation:           []string{},
	ListAlarmsOperation:        []string{},
	ListOccurrencesOperation:   []string{},
	ListProfilesOperation:      []string{},
	ListRoomsOperation:         []string{},
	ListSoundsOperation:        []string{},
	PreviewSoundOperation:      []string{},
	SelectAudioOutputOperation: []string{},
	SetVolumeOperation:         []string{},
	SnoozeAlarmOperation:       []string{},
	StopPlaybackOperation:      []string{},
	StreamEventsOperation:      []string{},
	UpdateAlarmOperation:       []string{},
}

// GetRolesForAccessToken returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAccessToken(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAccessToken(operation string) []string {
	roles, ok := operationRolesAccessToken[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityAccessToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.AccessToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"AccessToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
